"""Add status column to report_category model

Revision ID: 95c19a94006d
Revises: dc8cd7d8f291
Create Date: 2023-06-24 03:30:20.259725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c19a94006d'
down_revision = 'dc8cd7d8f291'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_category', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_category', 'status')
    # ### end Alembic commands ###
